### ISSUE TITLE
Several issues with the code - is this project abandoned, new maintainer needed ?

### ISSUE THREAD

**Issue by karlitos** [w8r/Leaflet.Tooltip#8]
#5 is caused by passing the _this_ (context) in
```javascript
this._map.on('zoomend', this.updatePosition, this);
```
which causes _point_ in _updatePosition_ being set to zoom-event.

Secondly, the _updatePosition_ function does not update the _latlng_ property. Causing issues in following scenario:

1. create "off-screen" tooltip by setting some _L.LatLng_ position
2. call _updatePosition(coordinates)_ and pass some screen coordinates as _L.Point_
3. Set content - this calls _updatePosition()_ without parameters, so the _point_ is being computed from the previous (off-screen) L.LatLng position and the tooltip "dissapears"
My fix was:
```javascript
updatePosition: function(point) {
...
    if (!point) {
        point = this._map.latLngToLayerPoint(this._latlng);
   }
   else {
        // new position defined, do not forget to update the _latlng
        this._latlng = this._map.layerPointToLatLng(point);
   }
...
```

If you hide the tooltip with _.hide()_ and update the position, the tooltip will be visible again. This could be fixed with:

```javascript
_getOffset: function(point, position) {
    ...
   var className = options.className + ' ' + position;
   if (L.DomUtil.hasClass(this._container, this.options.showClass)) {
       className = className + ' ' + options.showClass;
  }
  this._container.className = className;
  ...
}
```
This project was not very active in the last months, should I prepare a PR or does the project needs a new maintainer in general ?

**Comment by w8r** [comment]
Thank you very much, I will make the changes

**Comment by karlitos** [comment]
Thank you! I just tested the version 1.4 from NPM and it seems to be working nicely.
